#!/usr/bin/env bash
set -e

rm -f /opt/ar-io-node/.env
rm -f /opt/ar-io-node/docker-compose.yaml

instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

# DB backups can take an hour or more, this will timeout in CodeDeploy
# Disabling for now. Moving it to a cron job later.

# create backup dirs
# mkdir -p /efs/backups/$instance_id/sqlite/previous-before-install
# mkdir -p /efs/backups/$instance_id/sqlite/before-install

# keep an archive of the previous backup in case the copy fails
# #if [ "$(ls /efs/backups/$instance_id/before-install/*.db)" ]; then
#   mv /efs/backups/$instance_id/before-install/* /efs/backups/$instance_id/previous-before-install/
# fi

# # copy the live DBs to the backup directory
# if [ "$(ls /data/sqlite/*.db)" ]; then
#   cp /data/sqlite/*.db /efs/backups/$instance_id/sqlite/before-install/
# fi
