#!/bin/bash

if [[ "$1" = "" ]]
then
  echo "Usage: scripts/deploy-revision <REVISION>"
  exit 1
fi

revision=$1
environment="resources/.env.terraform"
archiveFile="${revision}.tar.gz"
archivePath="revisions/archives/${archiveFile}"
revisionPath="revisions/${revision}"
revisionBucket=$(. "$environment" && terraform output -raw CodeDeployBucket)
codeDeployAppName=$(. "$environment" && echo "ar-io-nodes-${TF_VAR_alias}")

echo "Creating archive..."
find $revisionPath -printf "%P\n" | \
tar -czf "$archivePath" --no-recursion -C "$revisionPath" -T -

echo "Uploading archive to S3..."
. "$environment" && aws s3 cp "$archivePath" "s3://${revisionBucket}/${archiveFile}"

echo "Deploying with CodeDeploy..."
. "$environment" && aws deploy create-deployment \
--region "$TF_VAR_region" \
--application-name "$codeDeployAppName" \
--deployment-config-name CodeDeployDefault.OneAtATime \
--deployment-group-name "$codeDeployAppName" \
--s3-location "bucket=${revisionBucket},bundleType=tgz,key=${archiveFile}" \
--description "Deploying revision ${revision} to ${codeDeployAppName}"

. "$environment" && echo "https://${TF_VAR_region}.console.aws.amazon.com/codesuite/codedeploy/deployments"