#!/bin/bash

revision=$1
environment="resources/.env.terraform"
archiveFile="${revision}.tar.gz"
archivePath="revisions/archives/${archiveFile}"
revisionPath="revisions/${revision}"

. "$environment"

find $revisionPath -printf "%P\n" | \
tar -czf "$archivePath" --no-recursion -C "$revisionPath" -T -

revisionBucket=$(. "$environment" && terraform output -raw CodeDeployBucket)
. "$environment" && aws s3 cp "$archivePath" "s3://${revisionBucket}/${archiveFile}"

codeDeployAppName="ar-io-nodes-${TF_VAR_alias}"
. "$environment" && aws deploy create-deployment \
--region "$TF_VAR_region" \
--application-name "$codeDeployAppName" \
--deployment-config-name CodeDeployDefault.OneAtATime \
--deployment-group-name "$codeDeployAppName" \
--s3-location "bucket=${revisionBucket},bundleType=tgz,key=${archiveFile}" \
--description "Deploying revision ${revision} to ${codeDeployAppName}"